AspNetCore/Models/ErrorViewModel.cs
using System;

namespace AspNetCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AspNetCore/Models/SuperHero.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetCore.Models
{
    public class SuperHero
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string AlterEgo { get; set; }
        public string PrimarySuperheroAbility { get; set; }
        public string SecondarySuperheroAbility { get; set; }
        public string Catchphrase { get; set; }
     
    }
}

AspNetCore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AspNetCore.Models;

namespace AspNetCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AspNetCore/Controllers/SuperHeroesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspNetCore.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using AspNetCore.Data;
namespace AspNetCore.Controllers
{
    public class SuperHeroesController : Controller
    {
        ApplicationDbContext context;
        public SuperHeroesController(ApplicationDbContext context)
        {
            this.context = context;
        }
        // GET: SuperHeroes
        public ActionResult Index()
        {
            var superHeroes = context.superHeroes.ToList();
            return View(superHeroes);
        }

        // GET: SuperHeroes/Details/5
        public ActionResult Details(int id)
        {
            var superheroInDb = context.superHeroes.Where(s => s.Id == id).FirstOrDefault();
            return View(superheroInDb);
        }

        // GET: SuperHeroes/Create
        public ActionResult Create()
        {
            SuperHero superHero = new SuperHero();
            return View(superHero);
        }

        // POST: SuperHeroes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SuperHero superHero)
        {
            try
            {
                // TODO: Add insert logic here
                context.superHeroes.Add(superHero);
                context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(superHero);
            }
        }

        // GET: SuperHeroes/Edit/5
        public ActionResult Edit(int id)
        {
            var superheroInDb = context.superHeroes.Where(s => s.Id == id).FirstOrDefault();
            return View(superheroInDb);
        }

        // POST: SuperHeroes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, SuperHero superHero)
        {
            try
            {
                // TODO: Add update logic here
                var superheroInDb = context.superHeroes.Where(s => s.Id == id).FirstOrDefault();
                context.superHeroes.Remove(superheroInDb);
                context.superHeroes.Add(superHero);
                context.SaveChanges();
                return View (superHero);
            }
            catch
            {
                return View(superHero);
            }
        }

        // GET: SuperHeroes/Delete/5
        public ActionResult Delete(int id)
        {
            var superheroInDb = context.superHeroes.Where(s => s.Id == id).FirstOrDefault();
            return View(superheroInDb);
        }

        // POST: SuperHeroes/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(SuperHero superHero)
        {
            try
            {
                // TODO: Add delete logic here
                context.Remove(superHero);
                context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AspNetCore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Super Hero Creator</h1>
    <p>Here you can create or edit your favorite Superhero and store it to our list!</p>
</div>

<center>
    <p><img src="https://www.pngkey.com/png/full/15-157883_boros-the-conqueror-of-galaxies-vs-goku-super.png" width="618" height="628" /></p>
</center>

AspNetCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNetCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AspNetCore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SuperHeroes" asp-action="Index">Super Heroes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - AspNetCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

AspNetCore/Views/SuperHeroes/Create.cshtml
@model AspNetCore.Models.SuperHero

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>SuperHero</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AlterEgo" class="control-label"></label>
                <input asp-for="AlterEgo" class="form-control" />
                <span asp-validation-for="AlterEgo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrimarySuperheroAbility" class="control-label"></label>
                <input asp-for="PrimarySuperheroAbility" class="form-control" />
                <span asp-validation-for="PrimarySuperheroAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondarySuperheroAbility" class="control-label"></label>
                <input asp-for="SecondarySuperheroAbility" class="form-control" />
                <span asp-validation-for="SecondarySuperheroAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Catchphrase" class="control-label"></label>
                <input asp-for="Catchphrase" class="form-control" />
                <span asp-validation-for="Catchphrase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AspNetCore/Views/SuperHeroes/Delete.cshtml
@model AspNetCore.Models.SuperHero

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SuperHero</h4>
    <hr />
    <center>
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.AlterEgo)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.AlterEgo)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PrimarySuperheroAbility)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PrimarySuperheroAbility)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.SecondarySuperheroAbility)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.SecondarySuperheroAbility)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Catchphrase)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Catchphrase)
            </dd>
        </dl>
    </center>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AspNetCore/Views/SuperHeroes/Details.cshtml
@model AspNetCore.Models.SuperHero

@{
    ViewData["Title"] = "Details";
}

    <center>
        <h1>Details</h1>

        <div>
            <h4>Superhero</h4>
            <hr />
                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Name)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.AlterEgo)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.AlterEgo)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.PrimarySuperheroAbility)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.PrimarySuperheroAbility)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.SecondarySuperheroAbility)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.SecondarySuperheroAbility)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Catchphrase)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Catchphrase)
                    </dd>
                </dl>
        </div>
        <div>
            <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
            <a asp-action="Index">Back to List</a>
        </div>
    </center>

AspNetCore/Views/SuperHeroes/Edit.cshtml
@model AspNetCore.Models.SuperHero

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>SuperHero</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AlterEgo" class="control-label"></label>
                <input asp-for="AlterEgo" class="form-control" />
                <span asp-validation-for="AlterEgo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrimarySuperheroAbility" class="control-label"></label>
                <input asp-for="PrimarySuperheroAbility" class="form-control" />
                <span asp-validation-for="PrimarySuperheroAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondarySuperheroAbility" class="control-label"></label>
                <input asp-for="SecondarySuperheroAbility" class="form-control" />
                <span asp-validation-for="SecondarySuperheroAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Catchphrase" class="control-label"></label>
                <input asp-for="Catchphrase" class="form-control" />
                <span asp-validation-for="Catchphrase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AspNetCore/Views/SuperHeroes/Index.cshtml
@model IEnumerable<AspNetCore.Models.SuperHero>

@{
    ViewData["Title"] = "Index";
}

<h1>Superheroes</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
          
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id"> @Html.DisplayFor(modelItem => item.Name)</a>
</td>            
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>